export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_ALL_USERS = 'GET_ALL_USERS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';

export const SEARCH_USER_VAL = 'SEARCH_USER_VAL';
export const SEARCH_MESSAGE_VAL = 'SEARCH_MESSAGE_VAL';

export const ADD_CHAT = 'ADD_CHAT';
export const GET_ALL_CHATS = 'GET_ALL_CHATS';

export const UPDATE_CHATNAME = 'UPDATE_CHATNAME';

export const SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE';
export const GET_PRIVATE_MESSAGES = 'GET_PRIVATE_MESSAGES';
